---
title: "Project Manual"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

# Stages {#stages}

There are several stages of the project:

1. identify as many measures as possible that assess externalizing problems and related constructs (and obtain the freely available ones)
    - fill out the [`Measures`](https://docs.google.com/spreadsheets/d/1luduZayyVmONdxBCcvrMGVv1vshhHzQ7eEOLg1aaMxE/edit#gid=0) tab of the `Existing Measures and Items` spreadsheet
    - add the instrument (as documents/PDFs) to the [`Instruments`](https://drive.google.com/drive/u/0/folders/1UL9_9tbKPQeKNLftlBTdWI9kVcqEn51f) folder
1. obtain as many measures as possible that are not freely available
    - i.e., add additional instruments to the [`Instruments`](https://drive.google.com/drive/u/0/folders/1UL9_9tbKPQeKNLftlBTdWI9kVcqEn51f) folder
1. identify the scales and subscales for each measure
    - i.e., fill out the [`Scales and Subscales`](https://docs.google.com/spreadsheets/d/1luduZayyVmONdxBCcvrMGVv1vshhHzQ7eEOLg1aaMxE/edit#gid=618359966) tab of the `Existing Measures and Items` spreadsheet
1. identify the items for each scale and subscale for each measure
    - i.e., fill out the [`Items`](https://docs.google.com/spreadsheets/d/1luduZayyVmONdxBCcvrMGVv1vshhHzQ7eEOLg1aaMxE/edit#gid=1930981316) tab of the `Existing Measures and Items` spreadsheet
1. identify the facet assessed by each item
    - i.e., fill in the `facet` column of the [`Items`](https://docs.google.com/spreadsheets/d/1luduZayyVmONdxBCcvrMGVv1vshhHzQ7eEOLg1aaMxE/edit#gid=1930981316) tab of the `Existing Measures and Items` spreadsheet
1. select and edit the items to ensure each facet is assessed comprehensively at each age
1. have the focus groups of experts review, refine, and rate the construct relevance of the items at each age
1. select the final item pool for each age
1. recruit participants to test the item pools
1. select items for the final measure at a given age for a given rater type based on testing
1. recruit a nationally representative sample of participants whose informants who will rate them on the measure
1. generate age- and sex-based norms
1. develop a computerized adaptive test
1. develop a computerized scoring system
1. develop translated versions

# Instructions for all Spreadsheets

- Use Roboto font size 10
- Use an en dash (`–`; i.e., not a hyphen) to indicate a range:
    - e.g., 1–18 (not 1-18)

# Stage 1: Identify Measures {#identifyMeasures}

This stage involves 1) identifying as many measures as possible that assess externalizing problems and related constructs and 2) obtaining the freely available ones.
To achieve this, conduct a thorough literature search using the suggested search terms ([below](#searchTerms)).
As you identify measures, fill out the `Measures` tab of the `Existing Measures and Items` spreadsheet and (if the instrument is freely available) add the instrument to the `Instruments` folder.

## Search Terms {#searchTerms}

The following are search terms to use for identifting measures that assess externalizing problems and related constructs:

- externalizing
- antisocial
- disruptive
- conduct problems
- callous-unemotional
- aggression
- oppositionality
- inattention
- hyperactivity
- ADHD
- conduct disorder
- oppositional defiant disorder
- antisocial personality disorder

## Fill out the `Measures` tab {#measuresTab}

Fill out The `Measures` tab of the `Existing Measures and Items` spreadsheet, located [here](https://docs.google.com/spreadsheets/d/1luduZayyVmONdxBCcvrMGVv1vshhHzQ7eEOLg1aaMxE/edit#gid=0).
If there are multiple editions of the same measure, select (and specify) the most recent edition (e.g., `Behavior Rating Inventory of Executive Function–2` for the 2nd Edition of the BRIEF).

#### Data Dictionary {#dataDictionary}

- `measureName`: the full official measure name
- `abbreviation`: the (capitalized) abbreviation of the measure name; duplicates are allowed
- `measureClass`: the broader assessment family/system; if multiple measures are from the same assessment family/system (e.g., both the Child Behavior Checklist and Teacher's Report Form are part of the Achenbach System of Empirically Based Assessment) provide a short label for the measure class; if the measure is not part of a broader measure class, use the lowercase version of the abbreviation
    - should be lowercase with no punctuation
    - only measures that are part of the same measure class should have the same label for `measureClass`; if measures from a different measure class have the same label for `measureClass`, this may have to include a disambuating element (such as the author name or year of publication) so measures from different measure classes are not given the same label
- `instrument`: the lowercase version of the abbreviation
    - should be lowercase with no punctuation
    - this may have to include a disambuating element (such as the author name or year of publication) so that there are no duplicates in the `measure` column
- `measure`: a calculated field that combines the `measureClass` and the `instrument` into one field, separated by an underscore; there should be no duplicates (duplicates are highlighted in red)
    - do **not** enter this manually; drag the formula from other cells in the column to calculate
- `type`: the type of measure; one of:
    - `questionnaire`
    - `interview`
    - `observation`
    - `other`
- rater: the rater for whom the measure was designed to be completed; one of:
    - `parent`
    - `teacher`
    - `teacher/caregiver`
    - `self`
    - `friend`
    - `clinician`
    - `other`
- `ageLowerYears`: the lower limit of the ratee's age range for which the measure was designed to be completed (in years)
- `ageUpperYears`: the upper limit of the ratee's age range for which the measure was designed to be completed (in years)
- `ageLowerMonths`: the lower limit of the ratee's age range for which the measure was designed to be completed (in months)—especially relevant for infants/toddlers
    - this is calculated automatically using a formula based on `ageLowerYears`, so you should not enter this unless the measure specifies ratee's age range in months rather than years
- `ageUpperMonths`: the upper limit of the ratee's age range for which the measure was designed to be completed (in months)—especially relevant for infants/toddlers
    - this is calculated automatically using a formula based on `ageUpperYears`, so you should not enter this unless the measure specifies ratee's age range in months rather than years
- `responseOptions`: the response options for each item
    - Use a semicolon (`;`) to separate response options
    - For example: `0=Not True (as far as you know); 1=Somewhat or Sometimes True; 2=Very True or Often True`
- `proprietary`: whether the measure is proprietary; one of:
    - `yes`
    - `no`
- `notes`: any notes on the measure
- `url`: the URL for the measure
- `keyReferences`: any key references for the measure, including seminal references, references that include the items, etc.

### How Rows are Sorted

The rows inthe `Measures` tab of the `Existing Measures and Items` spreadsheet are sorted by the `measure` column, which sorts first by `measureClass` and then by `instrument`.
When adding rows for new measures, place the new row in the appropriate location accordingly.

### How to Indicate Measures from the Same "Measure Class"

As described in the [Data Dictionary](#dataDictionary), the "measure class" is the broader assessment family or system.
Multiple instruments can belong to the same measure class (e.g., both the Child Behavior Checklist and Teacher's Report Form are part of the Achenbach System of Empirically Based Assessment).
If there are multiple measures within the same measure class, use borders to indicate that measures have the same measure class.
For instance, the first assessment in a given measure class should have a top border, and the last assessment in a given measure class should have a bottom border.

## Add instruments to the `Instruments` folder {#addInstruments}

If the instrument is freely available—i.e., publicly available or provided in a publication—add the instrument to the `Instruments` folder, located [here](https://drive.google.com/drive/u/0/folders/1UL9_9tbKPQeKNLftlBTdWI9kVcqEn51f).

# Stage 2: Obtain Measures {#obtainMeasures}

This stage involves obtaining as many measures as possible that are not freely available—e.g., measures that are proprietary (e.g., by purchasing them) or are not provided in publications (e.g., by contacting the authors).

# Stage 3: Identify the Scales and Subscales for Each Measure {#scalesSubscales}

# Stage 4: Identify the Items {#identifyItems}

# Stage 5: Identify the Facet Assessed by Each item {#identifyItemFacets}
